### ISSUE TITLE
Connection to container immediately terminates

### ISSUE THREAD

**Issue by gerneio** [blacktirion/email-oauth2-proxy-docker#21]
For me, when attempting to connect to the email proxy container from my local dev machine (windows PC) using the host port mapping and send an email via SMTP (for example), the connection just immediately closes. If I instead open a terminal directly to the email proxy container, I can send that SMTP email just fine. Additionally, if I create another container connected to same network (via compose auto-generated network), while that container can ping the email proxy container, it also won't connect to it via the container port mapping.

From host PC `telnet localhost 1587` just immediately terminates (no errors). If I try to use an SMTP sending utility, it says `Unable to read data from the transport connection: The connection was closed.`.

From the other container on the compose auto-generated network, the telnet command just says `telnet: can't connect to remote host (172.20.0.3): Connection refused`.

From within the email proxy container itself, the telnet command shows the proxied email server response as you would expect.

```shell
/app # telnet localhost 1587
Connected to localhost
220 SN7P220CA0017.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 14 Dec 2023 23:56:00 +0000
```

<details>
<summary>Here's my `compose.yaml` file</summary>

```yaml
version: '3.7'

services:
  test-connection:
    image: alpine
    container_name: test-connection
    # network_mode: "bridge"
    command:
      - /bin/sh
      - -c
      - | # Install `telnet` and check if we can reach `emailproxy`
        apk add busybox-extras
        telnet emailproxy 1587
        ping emailproxy -i 10
        ping 8.8.8.8
  emailproxy:
    image: blacktirion/email-oauth2-proxy-docker
    container_name: emailproxy
    volumes: [ ./config:/config ]
    ports: [ 1587:1587 ]
    # network_mode: "bridge"
    environment:
      LOGFILE: true
      DEBUG: true
```
</details>

Within my compose file, I've tried adjusting the network settings in various ways, such as using `network_mode: host` or `network_mode: bridge`, but I can't figure out why outside connections aren't going through to the email proxy container.

FYI, the same behavior occurs for both SMTP, IMAP & POP service ports.

Any ideas on where I could be going wrong here? Appreciate any direction you can provide here.
